// generated by longform/prep_long.py: every prepared long-form (longform/<id>/ -> src/longdata/<id>.json)
import type { LongData } from "../lib/long/types";
import longdemo from "./longdemo.json";
export const LONGDATA = [longdemo] as unknown as LongData[];
