"""The fourteen "○○ 특" v2 shorts, read by make.py. All of it is our own observational writing (창작): no facts are
claimed, and the people-type jokes (길치, 눈치 없는 사람) are about habits everyone has, told in the first person.

A line: (id, "nar" | "me", what is said, the two-line caption ("line 1 / line 2"), its picture[, (anchor, second picture)]).
"me" lines are the mascot's own reactions: about half as many as v1, captioned in quotes instead of a bubble.
Pictures: F = mascot close-up, P = photo (a key of photos.json), S = drawn scene (src/lib/Sseol.tsx).
"""
from make_lib import F, P, S, me

NAR_F = ("ko-KR-SunHiNeural", "+32%")            # about 6.5 syllables a second each (SunHi reads faster than Hyunsu at the same rate)
NAR_M = ("ko-KR-HyunsuMultilingualNeural", "+40%")
ME_F = ("ko-KR-SunHiNeural", "+32%", "+18Hz")
ME_M = ("ko-KR-InJoonNeural", "+40%", "+12Hz")
END = ("z", "nar", "여러분은 몇 개 해당?", "여러분은 몇 개 해당?ㅋㅋ")

EPISODES = {
 # ── new episodes (research/benchmark-drawn.md §3 idea list) ──
 "teuk9": dict(title="떡볶이 특", nar=NAR_M, me=ME_F, music=("music/hyperfun.mp3", 0.18), bg="#2e2321", lines=[
  ("a1", "nar", "일인분 시켰는데", "1인분 시켰는데", P("tbk_pan", react="shock", size=470, pop=-1)),
  ("a1b", "nar", "정신 차려 보면 볶음밥까지 먹고 있음.", "정신 차려 보면 / 볶음밥까지 먹고 있음",
   P("fried_kimchi", react="laugh", side="left", big="+볶음밥", bigat="a1b.볶음밥")),
  ("a2", "nar", "맵다면서 단무지만 세 번 리필함.", "맵다면서 / 단무지만 세 번 리필함",
   F("sick", "tilt", to="laugh", at="a2.젓가락", fx="fire", burst="#FF7A59")),
  ("c1", "me", "스읍 하 근데 맛있어.", "\"스읍… 하… 근데 맛있어\"", F("cry", "right", fx="sweat", prop="🌶️")),
  ("a3", "nar", "포장마차 어묵 국물은 세 번째 컵부터 눈치 보임.", "포장마차 어묵 국물 / 세 번째 컵부터 눈치 보임",
   P("tbk_eomuk", react="love", side="left", tag="마지막 한 입")),
  ("a4", "nar", "떡만 골라 먹는 친구랑 먹으면 어묵만 산더미.", "떡만 골라 먹는 친구랑 먹으면 / 어묵만 산더미",
   S(bg="store", chars=[{"name": "떡파", "color": "#FFF1D6", "mood": "angry"}, {"name": "어묵파", "color": "#E9B07A", "mood": "angry"}], big="VS", steps=[0, 0, 9, 0.15])),
  ("c2", "me", "그거 나야.", "\"…그거 나야\"", F("smug", "close", fx="sparkle", big="떡 승!")),
  ("a5", "nar", "밀떡이냐 쌀떡이냐로 친구랑 십 분 토론함.", "밀떡이냐 쌀떡이냐로 / 친구랑 10분 토론함", P("tbk_fork", react="think", tag="밀떡? 쌀떡?")),
  ("a6", "nar", "치즈 추가할까 고민하는 척 이미 손은 누르고 있음.", "치즈 추가할까 고민하는 척 / 이미 손은 누르고 있음",
   P("tbk_cheese", react="shy", side="left", big="+치즈", bigat="a6.이미")),
  ("a7", "nar", "김말이는 국물에 찍는 순간 반은 국물 속으로.", "김말이 국물에 찍는 순간 / 반은 국물 속으로", F("shock", "left", fx="sweat", prop="🍤")),
  ("a8", "nar", "당분간 안 먹는다 해 놓고 다음 날 점심 메뉴로 또 추천함.", "'당분간 안 먹어' 해 놓고 / 다음 날 점심에 또 추천함",
   S(bg="bedroom", chars=[me("sleep", to="think", size=1.25)], prop="💭", steps=[9, "a8.다음", "a8.다음", 9])),
  (*END, P("tbk_plate", react="happy", side="left")),
  ("y", "me", "난 벌써 배고파.", "\"난 벌써 배고파…ㅋㅋ\"", F("laugh", "close", fx="lines")),
 ]),
 "teuk10": dict(title="컵라면 특", nar=NAR_F, me=ME_M, music=("music/sneaky_snitch.mp3", 0.18), bg="#22262e", lines=[
  ("a1", "nar", "물 선까지 부으라는데", "물 선까지 부으라는데", P("cup", react="shock", size=470, pop=-1, tag="물 선?")),
  ("a1b", "nar", "그 선이 안 보임.", "그 선이 안 보임", F("shock", "close", fx="lines", prop="🍜", propX=0.82, propY=0.7, big="선 어디?", bigat=0.0)),
  ("a2", "nar", "삼 분 기다리라는데 일 분째 젓가락 들고 대기.", "3분 기다리라는데 / 1분째 젓가락 들고 대기", P("cup2", react="smug", side="left", tag="2분 30초")),
  ("c1", "me", "꼬들꼬들해야 맛있지.", "\"꼬들꼬들해야 맛있지\"", F("smug", "right", fx="sparkle")),
  ("a3", "nar", "밤 열한 시 컵라면, 붓기는 내일의 나에게 맡김.", "밤 11시 컵라면 / 붓기는 내일의 나에게",
   S(bg="night", place="📍 밤 11시", chars=[me("love", size=1.2)], prop="🍜", steps=[9, 0.1, 9, 9])),
  ("a4", "nar", "뚜껑 접어서 앞접시로 쓰는 건 국룰.", "뚜껑 접어서 / 앞접시로 쓰는 건 국룰", F("smug", "left", prop="🍜", propX=0.8, propY=0.35)),
  ("a5", "nar", "국물은 안 마신다더니 결국 바닥까지 원샷.", "국물은 안 마신다더니 / 결국 바닥까지 원샷",
   F("laugh", "tilt", fx="sweat", prop="🥣", big="원샷", bigat="a5.바닥")),
  ("c2", "me", "아 짜다. 물 물.", "\"아 짜다… 물 물\"", F("sick", "low", fx="gloom", prop="🥤", propX=0.82, propY=0.35)),
  ("a6", "nar", "고르는 데 이십 분, 먹는 데 삼 분.", "고르는 데 20분 / 먹는 데 3분", P("ramyeon", react="think", tag="하나 더?")),
  ("a8", "nar", "나무젓가락은 꼭 삐뚤게 쪼개짐.", "나무젓가락은 / 꼭 삐뚤게 쪼개짐", F("angry", "right", prop="🥢", propX=0.2, propY=0.3)),
  ("a9", "nar", "뜨거운 물 부으면 안경에 김이 서림.", "뜨거운 물 부으면 / 안경에 김 서림", F("shock", "low", fx="steam", prop="👓", propX=0.8, propY=0.3)),
  ("a7", "nar", "다음엔 다른 맛 먹자 해 놓고 또 같은 맛 집어 듦.", "'다음엔 다른 맛' 다짐하고 / 또 같은 맛 집어 듦", S(bg="store", chars=[me("think", to="happy", size=1.2)], prop="🍜", steps=[9, 0.1, "a7.또", 9])),
  (*END, P("kettle", react="happy")),
  ("y", "me", "난 지금 물 끓이는 중.", "\"난 지금 물 끓이는 중\"", F("happy", "close", fx="steam")),
 ]),
 "teuk11": dict(title="붕어빵 특", nar=NAR_M, me=ME_F, music=("music/monkeys_spinning_monkeys.mp3", 0.18), bg="#2b2520", lines=[
  ("a1", "nar", "팥이냐 슈크림이냐", "팥이냐 슈크림이냐", P("bungeo1", react="think", size=470, pop=-1, tag="팥? 슈크림?")),
  ("a1b", "nar", "고르다가 결국 둘 다 삼.", "고르다가 결국 둘 다 삼", F("shock", "close", fx="lines", big="둘 다!", bigat="a1b.둘")),
  ("a2", "nar", "머리부터 먹냐 꼬리부터 먹냐로 성격 다 나옴.", "머리부터 먹냐 꼬리부터 먹냐 / 성격 다 나옴",
   F("think", "left", prop="🐟", propX=0.8, propY=0.72, big="머리? 꼬리?", bigat=0.0)),
  ("c1", "me", "난 무조건 꼬리부터.", "\"난 무조건 꼬리부터!\"", F("happy", "right", fx="sparkle")),
  ("a3", "nar", "갓 나온 거 한 입에 입천장 데고 말 잃음.", "갓 나온 거 한 입에 / 입천장 데고 말 잃음", F("shock", "tilt", fx="fire", burst="#FF8A5C", big="앗 뜨!", bigat="a3.입천장")),
  ("a4", "nar", "겨울에 현금 챙기는 이유 일 순위.", "겨울에 현금 챙기는 / 이유 1순위", P("bungeo2", react="love", side="left", tag="이유 1순위")),
  ("a5", "nar", "봉지에서 눅눅해지기 전에 걸으면서 다 먹음.", "봉지에서 눅눅해지기 전에 / 걸으면서 다 먹음",
   S(bg="street", place="📍 집 가는 길", chars=[me("happy", size=1.15)], prop="🐟", steps=[9, 0.1, 9, 9])),
  ("a6", "nar", "세 마리 샀는데 집에 오면 한 마리.", "세 마리 샀는데 / 집에 오면 한 마리", F("smug", "left", prop="🐟", big="3 → 1", bigat="a6.집에")),
  ("c2", "me", "진짜 저절로 없어졌어.", "\"진짜 저절로 없어졌어\"", F("shy", "close", fx="sweat")),
  ("a8", "nar", "천 원에 몇 마리인지로 물가 체감함.", "천 원에 몇 마리인지로 / 물가 체감함", S(bg="home", chars=[me("happy", size=1.2)], prop="🐟", steps=[9, 0.1, 9, 9])),
  ("a7", "nar", "파는 곳 발견하면 지도에 몰래 별표 침.", "파는 곳 발견하면 / 지도에 몰래 별표", P("bungeo3", react="love", tag="★ 저장")),
  (*END, P("bungeo4", react="happy", side="left")),
  ("y", "me", "난 오늘 슈크림 다섯 개.", "\"난 오늘 슈크림 다섯 개\"", F("laugh", "close", fx="lines")),
 ]),
 "teuk12": dict(title="삼겹살 특", nar=NAR_F, me=ME_M, music=("music/hustle.mp3", 0.18), bg="#2c2321", lines=[
  ("a1", "nar", "고기 굽는 사람은", "고기 굽는 사람은", P("grill1", react="cry", size=470, pop=-1)),
  ("a1b", "nar", "정작 한 점도 못 먹음.", "정작 한 점도 못 먹음", F("cry", "tilt", fx="gloom", prop="🥢", propX=0.2, propY=0.3)),
  ("a2", "nar", "다 익었냐고 물으면 대답은 늘 조금만 더.", "다 익었냐고 물으면 / 대답은 늘 '조금만 더'", F("think", "close", prop="🥓", propX=0.82, propY=0.72)),
  ("c1", "me", "이제 먹어도 돼?", "\"이제 먹어도 돼?\"", F("shy", "right", fx="sparkle")),
  ("a3", "nar", "쌈 싸 먹다가 입보다 쌈이 더 커짐.", "쌈 싸 먹다가 / 입보다 쌈이 더 커짐", P("ssam", react="shock", big="왕쌈", bigat="a3.입보다")),
  ("a4", "nar", "김치를 불판에 올리면 그때부터 진짜 시작.", "김치를 불판에 올리면 / 그때부터 진짜 시작", P("grill2", react="love", side="left", tag="진짜 시작")),
  ("a5", "nar", "옷에 밴 냄새로 엘리베이터 사람들이 내 저녁 메뉴 맞힘.", "엘리베이터 탄 사람들이 / 내 저녁 메뉴 맞힘",
   S(bg="home", chars=[me("neutral", to="shock", size=1.2)], prop="👕", steps=[9, 0.1, "a5.집에", 9])),
  ("a6", "nar", "배부르다면서 볶음밥은 꼭 시킴.", "배부르다면서 / 볶음밥은 꼭 시킴", P("fried_pan", react="laugh", side="left")),
  ("c2", "me", "볶음밥 배는 따로 있어.", "\"볶음밥 배는 따로 있어\"", F("smug", "close", fx="sparkle")),
  ("a8", "nar", "불판 갈아 드릴까요 물으면 배부른데 네 함.", "'불판 갈아 드릴까요?' / 배부른데 '네!'", F("love", "low", fx="steam")),
  ("a9", "nar", "마늘 안 먹는다더니 불판 위 마늘만 노림.", "마늘 안 먹는다더니 / 불판 위 마늘만 노림", F("smug", "left", prop="🧄", propX=0.8, propY=0.35)),
  ("a7", "nar", "마지막 한 점은 아무도 손 안 댐.", "마지막 한 점은 / 아무도 손 안 댐", F("shy", "tilt", prop="🥓", big="1점", bigat="a7.아무도")),
  (*END, F("happy", "left", fx="hearts")),
  ("y", "me", "그 한 점 내가 먹을게.", "\"그 한 점, 내가 먹을게\"", P("grill3", react="laugh")),
 ]),
 "teuk13": dict(title="길치 특", nar=NAR_M, me=ME_F, music=("music/scheming_weasel.mp3", 0.18), bg="#23282a", lines=[
  ("a1", "nar", "지도 켜고 걷는데", "지도 켜고 걷는데", F("shock", "close", fx="lines", prop="🧭", propX=0.82, propY=0.72)),
  ("a1b", "nar", "화살표는 계속 뒤를 가리킴.", "화살표는 계속 뒤를 가리킴",
   S(bg="street", chars=[me("think", to="shock", size=1.2)], big="뒤?!", steps=[9, 9, "a1b.뒤를", "a1b.뒤를"])),
  ("a2", "nar", "분명 왔던 길인데 처음 보는 동네.", "분명 왔던 길인데 / 처음 보는 동네", P("alley1", react="think")),
  ("c1", "me", "여기 어디야?", "\"여기 어디야…?\"", F("sad", "right", fx="gloom")),
  ("a3", "nar", "출구 번호 헷갈려서 역에서만 십 분 헤맴.", "출구 번호 헷갈려서 / 역에서만 10분 헤맴",
   S(bg="subway", place="📍 출구가 어디지", chars=[me("think", to="shock", size=1.2)], steps=[9, 9, "a3.역에서만", 9])),
  ("a4", "nar", "길 물어봐 놓고 반대로 걸어감.", "길 물어봐 놓고 / 반대로 걸어감", P("crossroad", react="laugh", side="left", tag="반대쪽!")),
  ("a5", "nar", "삼십 분 일찍 나와도 결국 지각.", "30분 일찍 나와도 / 결국 지각", F("cry", "tilt", fx="sweat", prop="⏰", propX=0.18, propY=0.3)),
  ("a6", "nar", "오른쪽이라고 하면 일단 왼쪽부터 봄.", "오른쪽이라고 하면 / 일단 왼쪽부터 봄", F("think", "left", big="← ? →", bigat=0.0)),
  ("c2", "me", "오른쪽이 어느 쪽이더라?", "\"오른쪽이 어느 쪽이더라?\"", F("shy", "low", fx="sweat")),
  ("a8", "nar", "화장실 다녀오면 내 자리를 못 찾음.", "화장실 다녀오면 / 내 자리를 못 찾음",
   S(bg="office", chars=[{"color": "#8FD3FF", "mood": "neutral"}, {"color": "#C9A7FF", "mood": "neutral"}, me("think", to="shock")], steps=[9, 9, "a8.못", 9])),
  ("a9", "nar", "엘리베이터에서 내리면 양쪽 다 가 봄.", "엘리베이터에서 내리면 / 양쪽 다 가 봄", F("think", "right", big="← →", bigat="a9.양쪽")),
  ("a7", "nar", "그래도 맛집 가는 길은 한 번에 찾음.", "그래도 맛집 가는 길은 / 한 번에 찾음", P("tbk_pan", react="love", tag="맛집은 직진")),
  (*END, F("happy", "right", fx="sparkle")),
  ("y", "me", "근데 여기 어디야?", "\"근데 여기 어디야?\"", P("map", react="shock", side="left")),
 ]),
 "teuk14": dict(title="눈치 없는 사람 특", nar=NAR_F, me=ME_M, music=("music/sneaky_snitch.mp3", 0.18), bg="#262330", lines=[
  ("a1", "nar", "다들 조용한데", "다들 조용한데", F("shock", "close", fx="lines", big="...?", bigat=0.0)),
  ("a1b", "nar", "혼자 이거 누가 시켰냐고 물어봄.", "혼자 이거 누가 / 시켰냐고 물어봄",
   S(bg="home", chars=[{"color": "#8FD3FF", "mood": "neutral"}, me("happy"), {"color": "#C9A7FF", "mood": "neutral", "to": "shock"}], prop="🍗", steps=[9, 0.1, "a1b.물어봄", 9])),
  ("a2", "nar", "결말 궁금하다니까 진짜 결말을 말해 줌.", "결말 궁금하다니까 / 진짜 결말을 말해 줌", F("smug", "left", prop="🎬")),
  ("c1", "me", "어? 이거 스포야?", "\"어? 이거 스포야?\"", F("shock", "right", fx="sweat")),
  ("a3", "nar", "단톡방 분위기 싸한데 혼자 이모티콘 폭탄.", "단톡방 분위기 싸한데 / 혼자 이모티콘 폭탄",
   S(chars=[me("happy")], chat={"title": "우리 반 (28)", "msgs": [{"name": "민지", "text": "아 그건 좀…"}, {"name": "준호", "text": "…"},
     {"text": "😆😆😆🎉🎉", "me": True, "unread": "26"}, {"text": "🥳🥳🥳", "me": True, "unread": "26"}]},
     bg="linear-gradient(180deg, #fff6e8 0%, #ffe9cf 100%)", steps=[9, 9, 9, 9, 0.1, 0.5, "a3.혼자", "a3.폭탄"])),
  ("a4", "nar", "회의 다 끝나 가는데 질문 있어요 하고 손 듦.", "회의 다 끝나 가는데 / '질문 있어요' 손 듦",
   S(bg="office", chars=[{"color": "#8FD3FF", "mood": "sleep"}, me("happy", hat="✋"), {"color": "#C9A7FF", "mood": "shock"}], steps=[9, 9, 9, 9])),
  ("a5", "nar", "마지막 한 조각 아무도 안 먹는 이유 모름.", "마지막 한 조각 / 아무도 안 먹는 이유 모름", P("lastslice", react="think", tag="마지막 1조각")),
  ("a6", "nar", "괜찮다고 하면 진짜 괜찮은 줄 앎.", "괜찮다고 하면 / 진짜 괜찮은 줄 앎", F("happy", "tilt", fx="sparkle")),
  ("c2", "me", "괜찮다며?", "\"괜찮다며?\"", F("think", "low")),
  ("a8", "nar", "다들 일어나는데 혼자 디저트 시킴.", "다들 일어나는데 / 혼자 디저트 시킴", F("happy", "right", prop="🍰", propX=0.2, propY=0.3)),
  ("a9", "nar", "깜짝 생일 파티 장소를 주인공 앞에서 물어봄.", "깜짝 생일 파티 장소를 / 주인공 앞에서 물어봄", S(bg="home", chars=[{"color": "#8FD3FF", "mood": "happy", "to": "shock"}, me("happy"), {"color": "#C9A7FF", "mood": "neutral"}], prop="🎂", steps=[9, 0.1, "a9.주인공", 9])),
  ("a7", "nar", "근데 이런 친구가 제일 솔직하고 착함.", "근데 이런 친구가 / 제일 솔직하고 착함", F("love", "close", fx="hearts")),
  (*END, P("cake", react="happy", side="left")),
  ("y", "me", "혹시 나야?", "\"혹시… 나야?\"", F("shock", "close", fx="lines")),
 ]),
 # ── v1 episodes re-made in the v2 look (same items, one-line titles, no title read, half the reactions) ──
 "teuk1": dict(title="월요일 아침 특", nar=NAR_F, me=ME_M, music=("music/hustle.mp3", 0.18), bg="#262a33", lines=[
  ("a1", "nar", "알람은 다섯 번 끄고", "알람은 다섯 번 끄고", F("shock", "close", fx="lines", prop="⏰", propX=0.82, propY=0.72, big="×5", bigat=0.0)),
  ("a1b", "nar", "마지막 알람 이름은 진짜 최종 마지막.", "마지막 알람 이름이 / '진짜_최종_마지막'", S(bg="bedroom", chars=[me("sleep", size=1.25)], prop="⏰", steps=[9, 0.1, 9, 9])),
  ("c1", "me", "딱 오 분만.", "\"딱 5분만…!\"", P("alarm", react="sleep", side="left")),
  ("a2", "nar", "주말까지 며칠 남았는지 출근 전부터 셈.", "주말까지 며칠 남았는지 / 출근 전부터 셈", F("sad", "left", fx="gloom", big="D-5", bigat="a2.출근")),
  ("a3", "nar", "씻다가 그대로 다시 잠들 뻔함.", "씻다가 그대로 / 다시 잠들 뻔함", S(bg="bath", chars=[me("sleep", size=1.3)], prop="🪥", steps=[9, 0.1, 9, 9])),
  ("a4", "nar", "지하철에서 서서 졸다가 내릴 역 지나침.", "지하철에서 서서 졸다가 / 내릴 역 지나침",
   S(bg="subway", chars=[{"color": "#8FD3FF", "mood": "sleep"}, me("sleep", to="shock"), {"color": "#C9A7FF", "mood": "sleep"}], steps=[9, 9, "a4.내릴", 9])),
  ("c2", "me", "헉 여기 어디야?", "\"헉, 여기 어디야?\"", F("shock", "tilt", fx="sweat")),
  ("a5", "nar", "출입 카드 삑 소리가 하루 중 제일 슬픔.", "출입 카드 '삑' 소리가 / 하루 중 제일 슬픔", F("sad", "low", fx="gloom", prop="💨", propX=0.8, propY=0.3)),
  ("a6", "nar", "커피 마시기 전엔 메일을 읽어도 글자가 안 들어옴.", "커피 전엔 메일을 읽어도 / 글자가 안 들어옴", P("coffee", react="happy", tag="충전 완료")),
  ("a8", "nar", "엘리베이터 닫힘 버튼 괜히 연타.", "엘리베이터 닫힘 버튼 / 괜히 연타", F("angry", "left", prop="👆", propX=0.8, propY=0.35, big="연타", bigat="a8.연타")),
  ("a9", "nar", "퇴근까지 남은 시간 오전에만 열 번 계산.", "퇴근까지 남은 시간 / 오전에만 열 번 계산", F("think", "low", prop="🕐", propX=0.8, propY=0.25)),
  ("a7", "nar", "이렇게 버텼는데 아직 오전 열 시.", "이렇게 버텼는데 / 아직 오전 10시", F("cry", "right", fx="gloom", prop="🕙", propX=0.2, propY=0.3, big="10:00", bigat="a7.아직")),
  (*END, F("happy", "close", fx="sparkle")),
  ("y", "me", "난 일곱 개 다.", "\"난 7개 다…ㅋㅋ\"", F("laugh", "left", fx="lines")),
 ]),
 "teuk2": dict(title="시험 기간 특", nar=NAR_M, me=ME_F, music=("music/sneaky_snitch.mp3", 0.18), bg="#25283a", lines=[
  ("a1", "nar", "시험 전날만 되면", "시험 전날만 되면", F("shock", "close", fx="lines", prop="📚", propX=0.82, propY=0.72, big="D-1", bigat=0.0)),
  ("a1b", "nar", "갑자기 책상 정리가 하고 싶음.", "갑자기 책상 정리가 / 하고 싶음", S(bg="desk", chars=[me("happy", size=1.2)], prop="🧹", steps=[9, 0.1, 9, 9])),
  ("a2", "nar", "계획표 만드는 데만 한 시간 씀.", "계획표 만드는 데만 / 한 시간 씀", P("notes", react="smug", tag="계획 완벽")),
  ("c1", "me", "계획은 완벽해.", "\"계획은 완벽해\"", F("smug", "right", fx="sparkle")),
  ("a3", "nar", "평소엔 안 보던 다큐가 갑자기 꿀잼.", "평소엔 안 보던 다큐가 / 갑자기 꿀잼", S(bg="home", chars=[me("love", size=1.2)], prop="📺", steps=[9, 0.1, 9, 9])),
  ("a4", "nar", "십 분만 누웠는데 눈 떠 보니 아침.", "10분만 누웠는데 / 눈 떠 보니 아침", F("sleep", "low", to="shock", at="a4.아침", prop="☀️", propX=0.8, propY=0.25)),
  ("a5", "nar", "쉬는 시간 십 분에 제일 많이 외움.", "쉬는 시간 10분에 / 제일 많이 외움", F("think", "right", prop="📖", propX=0.2, propY=0.35)),
  ("c2", "me", "이거 나온다 이거!", "\"이거 나온다, 이거!\"", F("laugh", "left", fx="lines")),
  ("a6", "nar", "시험 끝나자마자 외운 거 전부 삭제.", "시험 끝나자마자 / 외운 거 전부 삭제", F("happy", "tilt", prop="🧠", propX=0.2, propY=0.3, big="삭제", bigat="a6.전부")),
  ("a8", "nar", "시험 범위 다시 물어보는 친구 꼭 한 명 있음.", "시험 범위 다시 묻는 친구 / 꼭 한 명 있음",
   S(bg="class", chars=[{"color": "#8FD3FF", "mood": "think"}, me("smug")], say={"who": 0, "text": "범위 어디까지야?"}, steps=[0.2, 9, 9, 9])),
  ("a9", "nar", "새벽 세 시에 갑자기 방 구조 바꾸고 싶음.", "새벽 3시에 갑자기 / 방 구조 바꾸고 싶음", F("shock", "right", fx="sparkle", prop="🛋️", propX=0.2, propY=0.3)),
  ("a7", "nar", "시험 끝나고 나니까 공부가 제일 잘됨.", "시험 끝나고 나니까 / 공부가 제일 잘됨", S(bg="desk", chars=[me("happy", size=1.2)], prop="📚", big="이제야?", steps=[9, 0.1, 9, "a7.공부가"])),
  (*END, F("happy", "close", fx="sparkle")),
  ("y", "me", "난 지금 책상 정리 중.", "\"난 지금 책상 정리 중\"", P("desk", react="laugh")),
 ]),
 "teuk3": dict(title="급식 특", nar=NAR_F, me=ME_M, music=("music/monkeys_spinning_monkeys.mp3", 0.18), bg="#2a2b24", lines=[
  ("a1", "nar", "사 교시부터", "4교시부터", F("love", "close", fx="hearts", prop="🍱", propX=0.82, propY=0.72)),
  ("a1b", "nar", "오늘 급식 메뉴만 생각함.", "오늘 급식 메뉴만 생각함", S(bg="class", sign="4교시", chars=[me("love", size=1.1)], prop="🍱", steps=[9, 0.1, 9, 9])),
  ("a2", "nar", "종 치자마자 뛰지 않고 아주 빠르게 걸어감.", "종 치자마자 뛰지 않고 / 아주 빠르게 걸어감",
   S(bg="cafeteria", chars=[me("happy", size=1.1)], big="경보 모드", steps=[9, 9, 9, 0.2])),
  ("c1", "me", "뛰는 거 아니에요!", "\"뛰는 거 아니에요!\"", F("shock", "right", fx="sweat")),
  ("a3", "nar", "줄 서서 앞에 몇 명 남았는지 계속 셈.", "줄 서서 앞에 / 몇 명 남았는지 계속 셈",
   S(bg="cafeteria", chars=[{"color": "#8FD3FF", "mood": "happy"}, {"color": "#C9A7FF", "mood": "neutral"}, me("think")], steps=[9, 9, 9, 9])),
  ("a4", "nar", "맛있는 반찬은 아껴 뒀다가 마지막에 먹음.", "맛있는 반찬은 아껴 뒀다 / 마지막에 먹음", P("chicken", react="love", tag="최애 반찬")),
  ("a5", "nar", "급식 국자가 한 번 더 오면 그날은 대성공.", "국자가 한 번 더 오면 / 그날은 대성공", F("happy", "tilt", fx="sparkle", prop="🍮", propX=0.2, propY=0.3)),
  ("c2", "me", "오늘 푸딩 나온대!", "\"오늘 푸딩 나온대!\"", F("laugh", "left", fx="lines")),
  ("a6", "nar", "친구가 안 먹는 반찬 슬쩍 노림.", "친구가 안 먹는 반찬 / 슬쩍 노림", F("smug", "low", prop="🥢", propX=0.82, propY=0.3)),
  ("a8", "nar", "급식표 보고 좋아하는 날은 동그라미.", "급식표 보고 / 좋아하는 날은 동그라미", F("happy", "right", prop="✏️", propX=0.2, propY=0.3)),
  ("a9", "nar", "카레 나오는 날은 복도 냄새부터 다름.", "카레 나오는 날은 / 복도 냄새부터 다름", F("love", "low", fx="steam", prop="🍛", propX=0.8, propY=0.3)),
  ("a7", "nar", "졸업하고 나니까 그 급식이 제일 그리움.", "졸업하고 나니까 / 그 급식이 제일 그리움", F("cry", "close", to="love", at="a7.그", fx="hearts", prop="🍱", propX=0.82, propY=0.72)),
  (*END, P("kimchi", react="happy", side="left")),
  ("y", "me", "난 아직도 사 교시면 배고파.", "\"난 아직도 4교시면 배고파\"", F("cry", "right", fx="sweat")),
 ]),
 "teuk4": dict(title="단톡방 특", nar=NAR_M, me=ME_F, music=("music/hyperfun.mp3", 0.18), bg="#232a33", lines=[
  ("a1", "nar", "알림은 꺼 놓고", "알림은 꺼 놓고", F("smug", "close", fx="sparkle", prop="📱", propX=0.82, propY=0.72, big="몰래 읽기", bigat=0.0)),
  ("a1b", "nar", "몰래 다 읽고 있음.", "몰래 다 읽고 있음",
   S(chars=[me("smug")], chat={"title": "동아리 (12)", "msgs": [{"name": "민지", "text": "이번 주 회식 어때?"}, {"name": "준호", "text": "난 좋아!"}, {"name": "지수", "text": "누구 대답 좀 ㅋㅋ"}]},
     bg="linear-gradient(180deg, #fff6e8 0%, #ffe9cf 100%)", steps=[9, 9, 9, 9, 0.05, 0.35, 0.65])),
  ("a2", "nar", "질문 올리면 아무도 대답 안 함.", "질문 올리면 / 아무도 대답 안 함",
   S(chars=[me("neutral", to="sad")], chat={"title": "우리 반 (28)", "msgs": [{"text": "내일 몇 시에 만나?", "me": True, "unread": "5"}]},
     bg="linear-gradient(180deg, #fff6e8 0%, #ffe9cf 100%)", steps=[9, 9, "a2.아무도", 9, 0.1])),
  ("c1", "me", "다들 어디 갔어?", "\"다들 어디 갔어…?\"", F("sad", "right", fx="gloom")),
  ("a3", "nar", "약속 잡자고 해 놓고 결국 안 만남.", "약속 잡자고 해 놓고 / 결국 안 만남",
   S(chars=[me("happy", to="sad")], chat={"title": "친구들 (4)", "msgs": [{"name": "민지", "text": "언제 한번 보자!"}, {"name": "준호", "text": "ㅇㅇ 꼭 보자"}, {"text": "좋아!", "me": True}]},
     bg="linear-gradient(180deg, #eef6ff 0%, #dbe9ff 100%)", steps=[9, 9, "a3.결국", 9, 0.1, 0.5, 0.9])),
  ("a4", "nar", "새벽 감성으로 보낸 톡 아침에 이불킥.", "새벽 감성으로 보낸 톡 / 아침에 이불킥", F("shy", "tilt", to="shock", at="a4.아침에", fx="sweat", prop="🌙", propX=0.2, propY=0.3)),
  ("a5", "nar", "엄마한테 보낼 톡을 단톡방에 보냄.", "엄마한테 보낼 톡을 / 단톡방에 보냄",
   S(chars=[me("happy", to="shock")], chat={"title": "우리 반 (28)", "msgs": [{"text": "엄마 나 오늘 늦어❤️", "me": True, "unread": "27"}]},
     bg="linear-gradient(180deg, #fff6e8 0%, #ffe9cf 100%)", steps=[9, 9, "a5.단톡방에", 9, 0.2])),
  ("c2", "me", "아 잘못 보냈어!", "\"아, 잘못 보냈어!\"", F("shock", "close", fx="lines")),
  ("a6", "nar", "숫자 일 사라지는지 계속 확인함.", "숫자 1 사라지는지 / 계속 확인함", P("phone", react="think", tag="1 → ?")),
  ("a8", "nar", "답장 타이밍 놓쳐서 영원히 못 보냄.", "답장 타이밍 놓쳐서 / 영원히 못 보냄", F("cry", "low", fx="sweat", prop="💬", propX=0.8, propY=0.3)),
  ("a9", "nar", "키읔 개수로 진심인지 판단함.", "ㅋ 개수로 / 진심인지 판단함",
   S(chars=[me("think")], chat={"title": "친구들 (4)", "msgs": [{"name": "민지", "text": "ㅋ"}, {"name": "준호", "text": "ㅋㅋㅋㅋㅋㅋㅋ"}]},
     bg="linear-gradient(180deg, #eef6ff 0%, #dbe9ff 100%)", steps=[9, 9, 9, 9, 0.1, 0.6])),
  ("a7", "nar", "막상 조용해지면 내가 먼저 심심해 보냄.", "막상 조용해지면 / 내가 먼저 '심심해' 보냄", F("shy", "left", prop="📱", propX=0.8, propY=0.35)),
  (*END, F("happy", "low", fx="sparkle")),
  ("y", "me", "난 안 읽은 톡 구십구 개.", "\"난 안 읽은 톡 99개\"", F("laugh", "right", fx="lines", big="99+", bigat=0.0)),
 ]),
 "teuk5": dict(title="자취 첫 달 특", nar=NAR_F, me=ME_M, music=("music/scheming_weasel.mp3", 0.18), bg="#2a2629", lines=[
  ("a1", "nar", "집이 너무 조용해서", "집이 너무 조용해서", F("shock", "close", fx="gloom", prop="🌙", propX=0.82, propY=0.25, big="고요…", bigat=0.0)),
  ("a1b", "nar", "오히려 잠이 안 옴.", "오히려 잠이 안 옴", S(bg="bedroom", chars=[me("shock", size=1.25)], prop="🌙", steps=[9, 0.1, 9, 9])),
  ("a2", "nar", "라면 끓인 냄비가 곧 그릇.", "라면 끓인 냄비가 / 곧 그릇", P("pot", react="happy", tag="설거지 -1")),
  ("c1", "me", "설거지 줄이는 거야.", "\"설거지 줄이는 거야\"", F("smug", "right", fx="sparkle")),
  ("a3", "nar", "대파 한 단은 끝까지 먹은 적이 없음.", "대파 한 단은 / 끝까지 먹은 적 없음", P("greenonion", react="sad", side="left")),
  ("a4", "nar", "휴지 없는 걸 마지막 한 칸에서 알게 됨.", "휴지 없는 걸 / 마지막 한 칸에서 앎", P("tissue", react="shock", tag="마지막 1칸")),
  ("a5", "nar", "빨래 돌려 놓고 까맣게 잊어버림.", "빨래 돌려 놓고 / 까맣게 잊어버림", F("think", "left", prop="🧺")),
  ("c2", "me", "아 빨래!", "\"아, 빨래!\"", F("shock", "tilt", fx="lines")),
  ("a6", "nar", "엄마 반찬통 돌려줄 때 빈 통 미안해서 과자 넣음.", "엄마 반찬통 돌려줄 때 / 빈 통 미안해서 과자 넣음", F("shy", "close", fx="hearts", prop="🍪", propX=0.82, propY=0.72)),
  ("a8", "nar", "최소 주문 금액 맞추다 보면 두 끼 분량.", "최소 주문 금액 맞추다 / 두 끼 분량 됨", F("shock", "low", prop="🛵", propX=0.8, propY=0.3, big="2인분", bigat="a8.두")),
  ("a9", "nar", "택배 오면 괜히 신나서 문 앞으로 달려감.", "택배 오면 괜히 신나서 / 문 앞으로 달려감", S(bg="door", chars=[me("happy", size=1.2)], prop="📦", steps=[9, 0.1, 9, 9])),
  ("a7", "nar", "자유롭다더니 한 달 뒤엔 본가 가는 날만 기다림.", "자유롭다더니 한 달 뒤 / 본가 가는 날만 기다림", F("cry", "left", fx="gloom", prop="🏠", propX=0.8, propY=0.35)),
  (*END, P("greenonion2", react="happy", side="left")),
  ("y", "me", "난 아직도 대파 남았어.", "\"난 아직도 대파 남았어\"", F("laugh", "right", fx="lines")),
 ]),
 "teuk6": dict(title="비 오는 날 특", nar=NAR_M, me=ME_F, music=("music/monkeys_spinning_monkeys.mp3", 0.18), bg="#222a30", lines=[
  ("a1", "nar", "우산 챙긴 날엔", "우산 챙긴 날엔", F("angry", "close", fx="lines", prop="☂️", propX=0.82, propY=0.72)),
  ("a1b", "nar", "비가 한 방울도 안 옴.", "비가 한 방울도 안 옴", S(bg="street", chars=[me("angry", size=1.2)], prop="☀️", big="맑음", steps=[9, 0.1, 9, 0.2])),
  ("a2", "nar", "우산 없는 날만 골라서 갑자기 소나기.", "우산 없는 날만 골라서 / 갑자기 소나기", S(bg="rain", chars=[me("shock", size=1.2)], steps=[9, 9, 9, 9])),
  ("c1", "me", "아니 왜 지금?", "\"아니, 왜 지금?!\"", P("rainwindow", react="cry", side="left")),
  ("a3", "nar", "집에 우산 많은데 또 하나 삼.", "집에 우산 많은데 / 또 하나 삼", P("umbrella", react="think", tag="우산 +1")),
  ("a4", "nar", "젖은 운동화에서 하루 종일 찌걱 소리.", "젖은 운동화에서 / 하루 종일 '찌걱' 소리", F("sick", "tilt", fx="sweat", prop="🧦", propX=0.2, propY=0.3)),
  ("a5", "nar", "비 오니까 파전 해 먹자 했는데 밀가루가 없음.", "비 오니까 파전 해 먹자 / 했는데 밀가루가 없음", P("pajeon", react="love", side="left")),
  ("c2", "me", "파전 먹으러 갈 사람?", "\"파전 먹으러 갈 사람?\"", F("happy", "left", fx="sparkle")),
  ("a6", "nar", "빗소리 들으면 잠이 쏟아짐.", "빗소리 들으면 / 잠이 쏟아짐", F("sleep", "low", fx="gloom", prop="🌧️", propX=0.8, propY=0.25)),
  ("a8", "nar", "우산 쓰고 걸어도 가방은 꼭 젖음.", "우산 쓰고 걸어도 / 가방은 꼭 젖음", F("sad", "right", fx="gloom", prop="🎒", propX=0.2, propY=0.3)),
  ("a9", "nar", "비 오는 날 버스는 꼭 더 늦게 오는 느낌.", "비 오는 날 버스는 / 더 늦게 오는 느낌",
   S(bg="rain", chars=[{"color": "#8FD3FF", "mood": "sad"}, me("angry")], steps=[9, 9, 9, 9])),
  ("a7", "nar", "집 도착하자마자 비 그침.", "집 도착하자마자 / 비 그침", S(bg="home", chars=[me("neutral", to="angry", size=1.2)], prop="🌤️", big="실화?", steps=[9, 0.1, "a7.비", "a7.비"])),
  (*END, F("happy", "close", fx="sparkle")),
  ("y", "me", "내일 우산 챙길까 말까.", "\"내일 우산 챙길까 말까…\"", F("think", "right", prop="☂️")),
 ]),
 "teuk7": dict(title="헬스장 첫 주 특", nar=NAR_F, me=ME_M, music=("music/Exhilarate.mp3", 0.16), bg="#2a2526", lines=[
  ("a1", "nar", "일단 회원권은", "일단 회원권은", F("smug", "close", fx="sparkle", prop="💳", propX=0.82, propY=0.72)),
  ("a1b", "nar", "일 년짜리부터 끊음.", "1년짜리부터 끊음", S(bg="gym", chars=[me("happy", size=1.25)], big="1년!", steps=[9, 9, 9, "a1b.끊음"])),
  ("a2", "nar", "운동복부터 풀세트로 장만함.", "운동복부터 / 풀세트로 장만", F("happy", "left", prop="👟")),
  ("c1", "me", "장비가 반이야.", "\"장비가 반이야\"", F("smug", "right", fx="lines")),
  ("a3", "nar", "기구 쓰는 법 몰라서 옆 사람 몰래 따라 함.", "기구 쓰는 법 몰라서 / 옆 사람 몰래 따라 함",
   S(bg="gym", chars=[{"color": "#8FD3FF", "mood": "happy"}, me("think")], steps=[9, 9, 9, 9])),
  ("a4", "nar", "첫날부터 너무 열심히 해 버림.", "첫날부터 / 너무 열심히 해 버림", P("dumbbell", react="angry", tag="의욕 200%")),
  ("a5", "nar", "다음 날 계단을 못 내려감.", "다음 날 / 계단을 못 내려감", P("stairs", react="cry", side="left")),
  ("c2", "me", "다리가 내 다리가.", "\"다리가… 내 다리가…\"", F("cry", "tilt", fx="sweat")),
  ("a6", "nar", "운동했으니까 치킨은 괜찮음.", "운동했으니까 / 치킨은 괜찮음", P("chicken", react="love")),
  ("a8", "nar", "거울 앞에서 근육 생겼나 매일 확인.", "거울 앞에서 / 근육 생겼나 매일 확인", F("smug", "tilt", prop="💪", propX=0.2, propY=0.3)),
  ("a9", "nar", "운동 끝나면 인증샷부터 찍음.", "운동 끝나면 / 인증샷부터 찍음", S(bg="gym", place="📸 오운완", chars=[me("happy", size=1.2)], steps=[9, 9, 9, 9])),
  ("a7", "nar", "결국 일 년 회원권으로 샤워만 하고 옴.", "결국 1년 회원권으로 / 샤워만 하고 옴", F("happy", "low", fx="steam", prop="🚿", propX=0.8, propY=0.3, big="샤워 완료", bigat="a7.샤워만")),
  (*END, F("happy", "close", fx="sparkle")),
  ("y", "me", "난 내일부터 진짜 간다.", "\"난 내일부터 진짜 간다\"", F("angry", "right", fx="fire", burst="#FF8A5C")),
 ]),
 "teuk8": dict(title="월급날 특", nar=NAR_M, me=ME_F, music=("music/hustle.mp3", 0.18), bg="#22302a", lines=[
  ("a1", "nar", "아침부터 입금 알림만", "아침부터 입금 알림만", F("love", "close", fx="sparkle", prop="📱", propX=0.82, propY=0.72, big="입금?", bigat=0.0)),
  ("a1b", "nar", "목 빠지게 기다림.", "목 빠지게 기다림", S(bg="office", chars=[me("think", to="love", size=1.2)], prop="📱", steps=[9, 0.1, "a1b.기다림", 9])),
  ("a2", "nar", "들어오자마자 카드값이 슝 빠져나감.", "들어오자마자 / 카드값이 슝 빠져나감", F("shock", "tilt", fx="lines", prop="💸", propX=0.2, propY=0.3)),
  ("c1", "me", "잠깐 내 월급.", "\"잠깐, 내 월급…!\"", F("cry", "right", fx="gloom")),
  ("a3", "nar", "점심은 괜히 비싼 메뉴로.", "점심은 괜히 / 비싼 메뉴로", P("steak", react="love", tag="오늘만")),
  ("a4", "nar", "오늘은 내가 쏜다 했다가 계산할 때 살짝 후회.", "'오늘은 내가 쏜다' / 계산할 때 살짝 후회", F("happy", "left", prop="🎁")),
  ("a5", "nar", "장바구니에 있던 거 전부 결제.", "장바구니에 있던 거 / 전부 결제", P("cart", react="smug", side="left", tag="전부 결제")),
  ("c2", "me", "이건 필요한 거야.", "\"이건 필요한 거야\"", F("smug", "low", fx="sparkle")),
  ("a6", "nar", "이번 달은 진짜 아끼자고 다짐함.", "이번 달은 진짜 / 아끼자고 다짐함", F("angry", "close", fx="fire", burst="#FF8A5C", big="절약!", bigat="a6.아끼자고")),
  ("a8", "nar", "통장 잔고 확인을 하루에 열 번 함.", "통장 잔고 확인 / 하루에 열 번", F("think", "right", prop="🏦", propX=0.2, propY=0.3)),
  ("a9", "nar", "월급날엔 괜히 회사가 덜 미움.", "월급날엔 괜히 / 회사가 덜 미움", S(bg="office", chars=[me("happy", size=1.2)], prop="💰", steps=[9, 0.1, 9, 9])),
  ("a7", "nar", "이틀 만에 잔고가 월급 전이랑 같아짐.", "이틀 만에 잔고가 / 월급 전이랑 같아짐", P("calendar", react="sad")),
  (*END, F("happy", "right", fx="sparkle")),
  ("y", "me", "월급아 어디 갔니.", "\"월급아, 어디 갔니…\"", F("cry", "close", fx="gloom")),
 ]),
}
