"""The picture plan for the Odyssey documentary: which image (or graphic) is on screen from which line.

Each chapter maps to a list of shots: (line, kind, args). `line` is the line index inside the chapter at
which the shot starts (a float starts it part-way through that line). Image shots are
("img", key, cx, cy, zoom, move): the frame is centred on (cx, cy) of the picture (0..1), `zoom` crops
in from a cover fit, and `move` is the Ken Burns drift ("in", "out", "l", "r", "u", "d").
Graphics: ("map", {...}) the route map, ("years", {...}) the 10-year bar, ("curse", {...}) the four
lines of the Cyclops' prayer, ("world", {}) / ("korea", {}) the Korea link, ("title", {}) the title card.
Keys are the image ids in sources.json.
"""

PLAN = {
    "prologue": [
        (0, "img", "nuijen_storm", .5, .45, 1.15, "in"),
        (1, "years", {"show": 10, "hl": None}),
        (2, "img", "lairesse_calypso", .55, .30, 1.6, "r"),
        (3, "img", "castiglione_circe", .45, .5, 1.25, "in"),
        (4, "years", {"show": 10, "hl": "sea"}),
        (5, "img", "tvt_helm", .55, .5, 1.3, "in"),
        (6, "img", "tvt_minerva_ithaca", .45, .5, 1.2, "l"),
        (6.6, "title", {}),
    ],
    "question": [
        (0, "img", "flaxman_demodocus", .5, .47, 2.1, "in"),
        (1, "years", {"show": 10, "hl": "poem"}),
        (2, "img", "nolin_alcinous", .5, .55, 1.9, "r"),
        (3, "img", "flaxman_demodocus", .62, .45, 3.0, "l"),
        (4, "img", "rubens_episodes", .5, .5, 1.1, "in"),
        (5, "img", "vinkeles_storm", .5, .5, 1.65, "r"),
        (6, "years", {"show": 10, "hl": "islands"}),
        (7, "img", "tvt_beggar", .62, .55, 1.4, "in"),
        (8, "img", "tvt_farewell", .62, .5, 1.5, "l"),
    ],
    "map": [
        (0, "map", {"mode": "direct", "show": ["troy"], "zoom": [1.0, 1.08], "focus": [.62, .45]}),
        (1, "map", {"mode": "direct", "show": ["troy", "ithaca"], "draw": [0, 1], "zoom": [1.05, 1.1], "focus": [.55, .5]}),
        (3, "img", "chodowiecki_penelope", .35, .5, 1.7, "in"),
        (4, "img", "tvt_bed", .97, .3, 2.8, "l"),
        (5, "img", "schelfhout_olive", .5, .4, 2.4, "u"),
        (6, "world", {}),
        (7, "korea", {}),
    ],
    "lotus": [
        (0, "img", "willaerts_wreck", .5, .5, 1.15, "in"),
        (1, "map", {"mode": "route", "upto": 2, "show": ["troy", "malea"], "zoom": [1.1, 1.25], "focus": [.68, .55]}),
        (3, "map", {"mode": "route", "upto": 3, "show": ["troy", "malea", "djerba"], "guess": ["djerba"], "zoom": [1.0, 1.05], "focus": [.5, .55]}),
        (4, "img", "tvt_lotus", .3, .5, 1.6, "r"),
        (6, "img", "tvt_lotus", .62, .5, 1.25, "in"),
        (8, "img", "zeeman_storm", .3, .5, 1.6, "l"),
        (10, "map", {"mode": "route", "upto": 3, "show": ["djerba"], "guess": ["djerba"], "zoom": [1.8, 1.95], "focus": [.25, .7]}),
    ],
    "cyclops": [
        (0, "img", "tvt_cyclops_land", .5, .5, 1.1, "in"),
        (2, "img", "tvt_cyclops_land", .62, .35, 1.8, "r"),
        (3, "img", "flaxman_polyphemus", .6, .42, 2.6, "in"),
        (5, "img", "tvt_grief", .5, .5, 1.15, "in"),
        (6, "img", "flaxman_polyphemus", .45, .5, 1.9, "l"),
        (8, "card", {"text": "\u201c내 이름은 \u2018아무도 아니\u2019다\u201d", "sub": "그리스어로 \u2018우티스(Outis)\u2019"}),
        (9, "img", "tvt_cave_sheep", .5, .5, 1.1, "in"),
        (12, "img", "tvt_grief", .3, .4, 1.8, "r"),
        (13, "img", "tvt_cave_sheep", .65, .6, 1.7, "r"),
    ],
    "name": [
        (0, "img", "tvt_rock_throw", .22, .6, 1.6, "in"),
        (2, "img", "tvt_rock_throw", .72, .12, 2.1, "l"),
        (4, "img", "vinkeles_storm", .4, .5, 2.1, "in"),
        (5, "card", {"text": "흔한 답 ① 신의 분노", "sub": "반쯤은 틀렸다"}),
        (6, "img", "neptune_messina", .5, .3, 1.6, "u"),
        (8, "curse", {"show": 0}),
        (9, "curse", {"show": 1}),
        (10, "curse", {"show": 2}),
        (11, "curse", {"show": 3}),
        (12, "curse", {"show": 4}),
        (13, "curse", {"show": 4, "remember": True}),
        (14, "map", {"mode": "route", "upto": 4, "show": ["troy", "djerba", "cyclops"], "guess": ["cyclops"], "zoom": [1.3, 1.45], "focus": [.42, .5]}),
    ],
    "wind": [
        (0, "map", {"mode": "route", "upto": 5, "show": ["cyclops", "aeolus"], "guess": ["aeolus"], "zoom": [1.6, 1.75], "focus": [.36, .42]}),
        (1, "img", "tvt_bag_gift", .45, .5, 1.25, "in"),
        (2, "img", "tvt_winds", .5, .45, 1.2, "in"),
        (3, "img", "tvt_helm", .45, .45, 1.6, "r"),
        (4, "map", {"mode": "route", "upto": 6, "show": ["aeolus", "ithaca"], "zoom": [1.35, 1.5], "focus": [.45, .45]}),
        (6, "img", "kobell_storm", .5, .5, 1.25, "in"),
        (7, "img", "vanthulden_bag", .5, .5, 1.15, "in"),
        (9, "img", "tvt_bag_open", .5, .5, 1.15, "in"),
        (10, "map", {"mode": "route", "upto": 7, "show": ["ithaca", "aeolus"], "zoom": [1.35, 1.45], "focus": [.45, .45]}),
        (11, "card", {"text": "첫 번째 잠", "sub": "고향을 빼앗다"}),
    ],
    "giants": [
        (0, "map", {"mode": "route", "upto": 8, "show": ["aeolus", "laestry"], "guess": ["laestry"], "zoom": [1.5, 1.6], "focus": [.25, .3]}),
        (1, "img", "ducros_coast", .5, .35, 1.6, "in"),
        (3, "img", "anon_laestrygonians", .5, .25, 1.7, "in"),
        (4, "img", "tvt_laestrygonians", .5, .5, 1.15, "in"),
        (5, "img", "tvt_rowing", .5, .5, 1.15, "r"),
        (6, "img", "tvt_laestrygonians", .3, .4, 1.8, "l"),
        (7, "fleet", {"from": 12, "to": 1}),
        (7.55, "curse", {"show": 4, "half": [2]}),
    ],
    "circe": [
        (0, "img", "tvt_circe_arrival", .5, .5, 1.1, "in"),
        (1, "img", "rubens_circe", .5, .5, 1.1, "in"),
        (2, "img", "castiglione_circe", .35, .55, 1.5, "r"),
        (3, "img", "trento_circe", .5, .5, 1.3, "in"),
        (4, "img", "vianen_tazza", .5, .45, 2.2, "l"),
        (5, "years", {"show": 10, "hl": "circe"}),
        (7, "img", "vianen_tazza", .5, .5, 1.35, "in"),
        (8, "card", {"text": "“이제는 집 생각을 하셔야 하지 않겠습니까”", "sub": "— 부하들"}),
        (9, "img", "tvt_circe_arrival", .4, .7, 1.8, "r"),
        (10, "img", "rubens_episodes", .3, .5, 1.8, "l"),
        (11, "card", {"text": "흔한 답 ② 험한 바다", "sub": "이 1년 동안 바다는 아무 짓도 하지 않았다"}),
    ],
    "underworld": [
        (0, "img", "fessard_tiresias", .5, .4, 1.5, "in"),
        (1, "img", "tvt_underworld", .5, .5, 1.1, "in"),
        (2, "img", "fessard_tiresias", .5, .4, 1.9, "r"),
        (3, "curse", {"show": 4, "echo": True}),
        (5, "img", "flaxman_ghosts", .5, .47, 2.0, "in"),
        (6, "img", "tvt_underworld", .25, .45, 1.8, "l"),
        (8, "img", "klinger_penelope", .45, .5, 1.25, "in"),
    ],
    "sirens": [
        (0, "map", {"mode": "route", "upto": 11, "show": ["circe", "sirens"], "guess": ["sirens"], "zoom": [1.8, 1.95], "focus": [.33, .25]}),
        (1, "img", "tvt_sirens", .5, .5, 1.15, "in"),
        (2, "img", "mignard_sirens", .5, .4, 1.5, "r"),
        (3, "img", "tvt_sirens", .3, .45, 1.8, "r"),
        (4, "img", "ducros_scilla", .5, .5, 1.6, "r"),
        (5, "img", "bauer_scylla", .5, .5, 1.15, "in"),
        (6, "img", "flaxman_scylla", .45, .5, 1.9, "in"),
        (7, "img", "tvt_rowing", .35, .6, 1.7, "l"),
        (8, "img", "mignard_sirens", .7, .45, 1.9, "r"),
    ],
    "cattle": [
        (0, "img", "messina_channel", .5, .22, 2.2, "r"),
        (1, "map", {"mode": "route", "upto": 13, "show": ["messina", "thrinacia"], "guess": ["thrinacia"], "zoom": [1.8, 1.95], "focus": [.37, .47]}),
        (2, "img", "rubens_circe", .3, .6, 1.8, "r"),
        (4, "img", "casembroot_storm", .5, .5, 1.15, "in"),
        (5, "img", "tvt_sacrifice", .5, .5, 1.15, "in"),
        (6, "card", {"text": "두 번째 잠", "sub": ""}),
        (7, "img", "tvt_sacrifice", .3, .55, 1.7, "r"),
        (10, "img", "baur_storm", .5, .5, 1.15, "in"),
        (11, "img", "watson_storm", .5, .5, 1.2, "l"),
        (12, "curse", {"show": 4, "done": [2]}),
    ],
    "calypso": [
        (0, "img", "willaerts_wreck", .55, .55, 1.7, "r"),
        (1, "map", {"mode": "route", "upto": 14, "show": ["thrinacia", "ogygia"], "guess": ["ogygia"], "zoom": [1.8, 1.95], "focus": [.33, .58]}),
        (2, "years", {"show": 10, "hl": "calypso"}),
        (4, "img", "lairesse_calypso", .66, .38, 2.4, "in"),
        (6, "img", "valck_calypso", .1, .4, 2.6, "l"),
        (7, "img", "kobell_storm", .3, .5, 1.6, "r"),
        (8, "card", {"text": "왜 10년이나 걸렸을까가 아니라", "sub": "늙지 않는 섬을 두고, 왜 굳이 돌아가려 했을까"}),
        (9, "img", "lairesse_mercury", .5, .35, 1.4, "d"),
        (10, "img", "lairesse_mercury", .9, .6, 2.4, "r"),
        (12, "img", "zeeman_storm", .75, .4, 1.8, "l"),
        (13, "img", "tvt_raft", .5, .5, 1.15, "in"),
        (13.6, "img", "basse_boat", .5, .72, 1.8, "r"),
    ],
    "raft": [
        (0, "map", {"mode": "route", "upto": 15, "show": ["ogygia", "scheria"], "guess": ["scheria"], "zoom": [1.4, 1.5], "focus": [.5, .5]}),
        (2, "img", "baur_storm", .4, .4, 1.6, "r"),
        (3, "img", "casembroot_storm", .35, .55, 1.6, "l"),
        (4, "img", "flaxman_leucothea", .76, .74, 2.6, "in"),
        (6, "img", "jordaens_nausicaa", .5, .5, 1.15, "in"),
        (7, "img", "sandrart_nausicaa", .5, .5, 1.15, "l"),
        (8, "img", "nolin_alcinous", .55, .6, 2.3, "in"),
    ],
    "ship": [
        (0, "img", "tvt_farewell", .5, .5, 1.1, "in"),
        (1, "curse", {"show": 4, "done": [2, 3]}),
        (2, "img", "flaxman_asleep", .5, .5, 1.6, "in"),
        (4, "card", {"text": "세 번째 잠", "sub": ""}),
        (5, "img", "watson_storm", .7, .4, 1.8, "in"),
        (6, "map", {"mode": "route", "upto": 16, "show": ["scheria", "ithaca"], "zoom": [2.0, 2.15], "focus": [.55, .38]}),
        (7, "img", "flaxman_asleep", .4, .62, 2.6, "r"),
    ],
    "home": [
        (0, "img", "tvt_wakes", .1, .65, 2.6, "in"),
        (1, "img", "tvt_wakes", .95, .62, 2.4, "r"),
        (2, "img", "tvt_minerva_ithaca", .5, .5, 1.15, "in"),
        (4, "curse", {"show": 4, "done": [1, 2, 3]}),
        (5, "img", "tvt_bow_feast", .45, .5, 1.6, "in"),
        (6, "img", "velijn_penelope", .5, .55, 1.5, "l"),
        (7, "curse", {"show": 4, "done": [1, 2, 3, 4]}),
    ],
    "nobody": [
        (0, "img", "flaxman_oldman", .5, .5, 2.0, "in"),
        (1, "img", "tvt_eumaeus", .5, .55, 1.15, "r"),
        (3, "img", "tvt_argos_lying", .95, .95, 2.2, "in"),
        (4, "img", "brown_argus", .6, .55, 1.7, "in"),
        (5, "img", "tvt_argos", .5, .6, 1.4, "in"),
        (6, "img", "flaxman_dog", .5, .5, 2.2, "in"),
        (7, "img", "tvt_argos_lying", .8, .9, 1.7, "u"),
        (8, "img", "penelope_weaving", .5, .5, 1.15, "r"),
        (9, "img", "picart_penelope", .5, .45, 1.3, "in"),
        (10, "img", "delattre_bow", .45, .5, 1.6, "in"),
    ],
    "reason": [
        (0, "years", {"show": 10, "hl": None}),
        (1, "years", {"show": 10, "hl": "islands"}),
        (2, "img", "neptune_messina", .5, .22, 2.3, "r"),
        (3, "img", "tvt_bag_open", .3, .6, 1.8, "l"),
        (4, "img", "trento_circe", .5, .35, 1.8, "d"),
        (5, "img", "valck_calypso", .12, .5, 2.2, "r"),
        (7, "curse", {"show": 4, "done": [1, 2, 3, 4], "loophole": True}),
        (9, "img", "tvt_raft", .65, .55, 1.8, "r"),
        (10, "card", {"text": "odyssey", "sub": "길고 험한 여정 — 이 10년에서 나온 말"}),
    ],
    "bed": [
        (0, "img", "penelope_statue", .5, .12, 1.5, "u"),
        (1, "img", "bartolozzi_meeting", .5, .45, 1.4, "in"),
        (2, "img", "burke_euryclea", .5, .5, 1.25, "in"),
        (3, "img", "tvt_minerva_penelope", .5, .5, 1.15, "l"),
        (5, "img", "tivoli_olive", .5, .4, 1.4, "u"),
        (6.5, "img", "schelfhout_olive", .45, .5, 2.4, "u"),
        (8, "bedtree", {}),
        (9, "img", "tvt_embrace", .5, .5, 1.15, "in"),
        (10, "img", "bartolozzi_meeting", .5, .35, 2.0, "in"),
    ],
    "epilogue": [
        (0, "years", {"show": 10, "hl": "islands"}),
        (1, "img", "tvt_bow_feast", .5, .3, 2.0, "r"),
        (2, "bedtree", {"still": True}),
        (4, "img", "tvt_argos", .45, .78, 1.9, "in"),
        (4.6, "img", "klinger_penelope", .3, .5, 1.8, "r"),
        (5, "img", "picart_penelope", .5, .55, 1.9, "in"),
        (6, "img", "tvt_embrace", .5, .4, 1.8, "in"),
        (7, "img", "flaxman_ghosts", .3, .5, 2.4, "r"),
        (8, "img", "ducros_coast", .25, .45, 2.0, "in"),
        (9, "img", "nuijen_storm", .7, .35, 1.6, "out"),
    ],
}
