"""Write src/lib/long/worldmap.ts: the world's land outline as one SVG path, for the map card (MapCard.tsx).

usage: python3 longform/worldmap.py <ne_50m_land.geojson>
Source: Natural Earth 1:50m land polygons (public domain, naturalearthdata.com), from
https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_land.geojson
Projection: plain equirectangular, x = (lon + 180) * 10, y = (90 - lat) * 10, so the path lives in a 3600 x 1800 box
and the card can zoom to any lon/lat window. Points closer than 0.15 degrees are dropped, and islands smaller
than about 0.3 square degrees are left out, which keeps the file small but Korea, Japan and Jeju still clear.
"""
import json, os, sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
g = json.load(open(sys.argv[1]))
def area(r):
    return abs(sum(r[i][0] * r[i + 1][1] - r[i + 1][0] * r[i][1] for i in range(len(r) - 1))) / 2
parts = []
for f in g["features"]:
    geo = f["geometry"]
    polys = geo["coordinates"] if geo["type"] == "MultiPolygon" else [geo["coordinates"]]
    for poly in polys:
        ring = poly[0]
        if area(ring) < 0.3: continue
        pts, last = [], None
        for lon, lat in ring:
            if last and abs(lon - last[0]) < 0.15 and abs(lat - last[1]) < 0.15: continue
            pts.append((round((lon + 180) * 10), round((90 - lat) * 10))); last = (lon, lat)
        if len(pts) < 4: continue
        d = f"M{pts[0][0]} {pts[0][1]}" + "".join(f"l{b[0] - a[0]} {b[1] - a[1]}" for a, b in zip(pts, pts[1:])) + "z"
        parts.append(d)
out = f"{HERE}/src/lib/long/worldmap.ts"
with open(out, "w") as fh:
    fh.write("// generated by longform/worldmap.py from Natural Earth 1:50m land (public domain). x = (lon + 180) * 10, y = (90 - lat) * 10\n")
    fh.write(f"export const LAND = \"{''.join(parts)}\";\n")
print(out, os.path.getsize(out), "bytes,", len(parts), "polygons")
